### PR TITLE
allow more than 9999 session and prevent the cpu from being eaten

### PR DESCRIPTION
**Pull request by FurriousFox**
instead of setting your house on fire when more than 9999 people login at once, consider not doing that instead (by just giving a slightly longer vanityUrl)

(also, my formatter deleted some random spaces you left on line 21 and 26)

### CODE REVIEW

**Comment by MattterSteege** [comment]
I have 2 things to note. I don't think that it is really necessary to make a system that complicated, mostly because there is (on average) 1 session active on a given time. (you can view of https://somtoday.kronk.tech, on the bottom of the page)
And a small thing might me that the `random` instance might be better of outside of the do-while loops, but this is a mistake i made too.

**Comment by FurriousFox** [comment]
Fair, this was more to prevent simple DOS attacks that would cause no new sessions to be made and it to eat your CPU on trying random numbers that have all been used, I'll improve my pr later today utilizing the Log function instead to remove a useless while loop and simplify the code.

**Comment by FurriousFox** [comment]
updated the pr, don't see why not to merge it, but it's up to you

**Comment by MattterSteege** [comment]
Forgot to day lgtm, so, LGTM

**Pull request merged**
